In [10]:
import numpy as np
import pandas as pd
import matplotlib
import matplotlib.pyplot as plt
import seaborn as sns
import datetime
import calendar

In [2]:
data = pd.read_csv("dla12.csv")
train=pd.read_csv("dla12.csv")
test=pd.read_csv("dla12.csv")

In [3]:
data.head()
train.describe(include='all')

,Unique Key,Created Date,Closed Date,Agency,Agency Name,Complaint Type,Descriptor,Location Type,Incident Zip,Incident Address,...,Bridge Highway Name,Bridge Highway Direction,Road Ramp,Bridge Highway Segment,Garage Lot Name,Ferry Direction,Ferry Terminal Name,Latitude,Longitude,Location
count,4.705000e+04,47050,46790,47050,47050,47050,46387,47050,46749.000000,41593,...,44,44,35,35,0.0,0.0,0.0,46648.000000,46648.000000,46648
unique,NaN,46764,44080,1,2,20,39,14,NaN,24970,...,17,23,2,34,NaN,NaN,NaN,NaN,NaN,28705
top,NaN,12/23/2015 06:33:50 PM,12/27/2015 08:59:15 PM,NYPD,New York City Police Department,Blocked Driveway,No Access,Street/Sidewalk,NaN,1207 BEACH AVENUE,...,FDR Dr,East/Queens Bound,Roadway,East 96th St (Exit 14) - Triborough Br (Exit 17),NaN,NaN,NaN,NaN,NaN,"(40.83036235589997, -73.86602154214397)"
freq,NaN,3,2,47050,47049,14876,11164,39052,NaN,244,...,8,5,28,2,NaN,NaN,NaN,NaN,NaN,244
mean,3.214980e+07,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10877.852168,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.719765,-73.927195,NaN
std,9.346085e+04,NaN,NaN,NaN,NaN,NaN,NaN,NaN,575.276739,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.080658,0.080596,NaN
min,3.197681e+07,NaN,NaN,NaN,NaN,NaN,NaN,NaN,83.000000,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.501279,-74.254937,NaN
25%,3.207253e+07,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10451.000000,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.661859,-73.977372,NaN
50%,3.215360e+07,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11211.000000,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.714674,-73.932869,NaN
75%,3.222959e+07,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11249.000000,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.766749,-73.872831,NaN
max,3.231065e+07,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11697.000000,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.911533,-73.700837,NaN

In [4]:
data.info

<bound method DataFrame.info of        Unique Key            Created Date             Closed Date Agency  \
0        32310363  12/31/2015 11:59:45 PM  01/01/2016 12:55:15 AM   NYPD
1        32309934  12/31/2015 11:59:44 PM  01/01/2016 01:26:57 AM   NYPD
2        32309159  12/31/2015 11:59:29 PM  01/01/2016 04:51:03 AM   NYPD
3        32305098  12/31/2015 11:57:46 PM  01/01/2016 07:43:13 AM   NYPD
4        32306529  12/31/2015 11:56:58 PM  01/01/2016 03:24:42 AM   NYPD
...           ...                     ...                     ...    ...
47045    31980666  11/14/2015 11:02:30 AM  11/14/2015 02:08:32 PM   NYPD
47046    31982224  11/14/2015 11:00:59 AM  11/14/2015 01:55:48 PM   NYPD
47047    31986021  11/14/2015 11:00:28 AM  11/14/2015 11:42:22 AM   NYPD
47048    31983677  11/14/2015 10:59:17 AM  11/14/2015 12:51:31 PM   NYPD
47049    31977067  11/14/2015 10:59:06 AM  11/14/2015 12:14:52 PM   NYPD

                           Agency Name           Complaint Type  \
0      New York City Police Department  Noise - Street/Sidewalk
1      New York City Police Department         Blocked Driveway
2      New York City Police Department         Blocked Driveway
3      New York City Police Department          Illegal Parking
4      New York City Police Department          Illegal Parking
...                                ...                      ...
47045  New York City Police Department         Blocked Driveway
47046  New York City Police Department         Blocked Driveway
47047  New York City Police Department             Animal Abuse
47048  New York City Police Department         Blocked Driveway
47049  New York City Police Department  Noise - Street/Sidewalk

                         Descriptor     Location Type  Incident Zip  \
0                  Loud Music/Party   Street/Sidewalk       10034.0
1                         No Access   Street/Sidewalk       11105.0
2                         No Access   Street/Sidewalk       10458.0
3      Commercial Overnight Parking   Street/Sidewalk       10461.0
4                  Blocked Sidewalk   Street/Sidewalk       11373.0
...                             ...               ...           ...
47045                Partial Access   Street/Sidewalk       11358.0
47046                     No Access   Street/Sidewalk       10310.0
47047                     Neglected  Store/Commercial       11370.0
47048                     No Access   Street/Sidewalk       10453.0
47049              Loud Music/Party   Street/Sidewalk       10007.0

            Incident Address  ... Bridge Highway Name  \
0        71 VERMILYEA AVENUE  ...                 NaN
1            27-07 23 AVENUE  ...                 NaN
2      2897 VALENTINE AVENUE  ...                 NaN
3        2940 BAISLEY AVENUE  ...                 NaN
4              87-14 57 ROAD  ...                 NaN
...                      ...  ...                 ...
47045       43-61 161 STREET  ...                 NaN
47046        614 CARY AVENUE  ...                 NaN
47047                    NaN  ...                 NaN
47048     1685 JEROME AVENUE  ...                 NaN
47049         CITY HALL PARK  ...                 NaN

      Bridge Highway Direction Road Ramp Bridge Highway Segment  \
0                          NaN       NaN                    NaN
1                          NaN       NaN                    NaN
2                          NaN       NaN                    NaN
3                          NaN       NaN                    NaN
4                          NaN       NaN                    NaN
...                        ...       ...                    ...
47045                      NaN       NaN                    NaN
47046                      NaN       NaN                    NaN
47047                      NaN       NaN                    NaN
47048                      NaN       NaN                    NaN
47049                      NaN       NaN                    NaN

      Garage Lot Name Ferry Direction Ferry Terminal Name   Latitude  \
0                 NaN             NaN                 NaN  40.865682
1                 NaN             NaN                 NaN  40.775945
2                 NaN             NaN                 NaN  40.870325
3                 NaN             NaN                 NaN  40.835994
4                 NaN             NaN                 NaN  40.733060
...               ...             ...                 ...        ...
47045             NaN             NaN                 NaN  40.758377
47046             NaN             NaN                 NaN  40.632028
47047             NaN             NaN                 NaN  40.759330
47048             NaN             NaN                 NaN  40.846368
47049             NaN             NaN                 NaN        NaN

       Longitude                                  Location
0     -73.923501   (40.86568153633767, -73.92350095571744)
1     -73.915094  (40.775945312321085, -73.91509393898605)
2     -73.888525  (40.870324522111424, -73.88852464418646)
3     -73.828379   (40.83599404683083, -73.82837939584206)
4     -73.874170  (40.733059618956815, -73.87416975810375)
...          ...                                       ...
47045 -73.805185  (40.758377273679386, -73.80518542890631)
47046 -74.122167  (40.632028408561006, -74.12216666543866)
47047 -73.885104   (40.75933008575395, -73.88510434923467)
47048 -73.913316   (40.84636809667345, -73.91331613201108)
47049        NaN                                       NaN

[47050 rows x 53 columns]>

In [5]:
data.tail()

,Unique Key,Created Date,Closed Date,Agency,Agency Name,Complaint Type,Descriptor,Location Type,Incident Zip,Incident Address,...,Bridge Highway Name,Bridge Highway Direction,Road Ramp,Bridge Highway Segment,Garage Lot Name,Ferry Direction,Ferry Terminal Name,Latitude,Longitude,Location
47045,31980666,11/14/2015 11:02:30 AM,11/14/2015 02:08:32 PM,NYPD,New York City Police Department,Blocked Driveway,Partial Access,Street/Sidewalk,11358.0,43-61 161 STREET,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.758377,-73.805185,"(40.758377273679386, -73.80518542890631)"
47046,31982224,11/14/2015 11:00:59 AM,11/14/2015 01:55:48 PM,NYPD,New York City Police Department,Blocked Driveway,No Access,Street/Sidewalk,10310.0,614 CARY AVENUE,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.632028,-74.122167,"(40.632028408561006, -74.12216666543866)"
47047,31986021,11/14/2015 11:00:28 AM,11/14/2015 11:42:22 AM,NYPD,New York City Police Department,Animal Abuse,Neglected,Store/Commercial,11370.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.759330,-73.885104,"(40.75933008575395, -73.88510434923467)"
47048,31983677,11/14/2015 10:59:17 AM,11/14/2015 12:51:31 PM,NYPD,New York City Police Department,Blocked Driveway,No Access,Street/Sidewalk,10453.0,1685 JEROME AVENUE,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.846368,-73.913316,"(40.84636809667345, -73.91331613201108)"
47049,31977067,11/14/2015 10:59:06 AM,11/14/2015 12:14:52 PM,NYPD,New York City Police Department,Noise - Street/Sidewalk,Loud Music/Party,Street/Sidewalk,10007.0,CITY HALL PARK,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
train.shape

(47050, 53)

In [7]:
data.describe()

,Unique Key,Incident Zip,X Coordinate (State Plane),Y Coordinate (State Plane),School or Citywide Complaint,Vehicle Type,Taxi Company Borough,Taxi Pick Up Location,Garage Lot Name,Ferry Direction,Ferry Terminal Name,Latitude,Longitude
count,4.705000e+04,46749.000000,4.664900e+04,46649.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,46648.000000,46648.000000
mean,3.214980e+07,10877.852168,1.004420e+06,201525.200840,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.719765,-73.927195
std,9.346085e+04,575.276739,2.234695e+04,29387.588114,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.080658,0.080596
min,3.197681e+07,83.000000,9.133570e+05,121998.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.501279,-74.254937
25%,3.207253e+07,10451.000000,9.905180e+05,180444.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.661859,-73.977372
50%,3.215360e+07,11211.000000,1.002851e+06,199687.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.714674,-73.932869
75%,3.222959e+07,11249.000000,1.019487e+06,218639.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.766749,-73.872831
max,3.231065e+07,11697.000000,1.067154e+06,271391.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.911533,-73.700837

In [8]:
data.describe

<bound method NDFrame.describe of        Unique Key            Created Date             Closed Date Agency  \
0        32310363  12/31/2015 11:59:45 PM  01/01/2016 12:55:15 AM   NYPD
1        32309934  12/31/2015 11:59:44 PM  01/01/2016 01:26:57 AM   NYPD
2        32309159  12/31/2015 11:59:29 PM  01/01/2016 04:51:03 AM   NYPD
3        32305098  12/31/2015 11:57:46 PM  01/01/2016 07:43:13 AM   NYPD
4        32306529  12/31/2015 11:56:58 PM  01/01/2016 03:24:42 AM   NYPD
...           ...                     ...                     ...    ...
47045    31980666  11/14/2015 11:02:30 AM  11/14/2015 02:08:32 PM   NYPD
47046    31982224  11/14/2015 11:00:59 AM  11/14/2015 01:55:48 PM   NYPD
47047    31986021  11/14/2015 11:00:28 AM  11/14/2015 11:42:22 AM   NYPD
47048    31983677  11/14/2015 10:59:17 AM  11/14/2015 12:51:31 PM   NYPD
47049    31977067  11/14/2015 10:59:06 AM  11/14/2015 12:14:52 PM   NYPD

                           Agency Name           Complaint Type  \
0      New York City Police Department  Noise - Street/Sidewalk
1      New York City Police Department         Blocked Driveway
2      New York City Police Department         Blocked Driveway
3      New York City Police Department          Illegal Parking
4      New York City Police Department          Illegal Parking
...                                ...                      ...
47045  New York City Police Department         Blocked Driveway
47046  New York City Police Department         Blocked Driveway
47047  New York City Police Department             Animal Abuse
47048  New York City Police Department         Blocked Driveway
47049  New York City Police Department  Noise - Street/Sidewalk

                         Descriptor     Location Type  Incident Zip  \
0                  Loud Music/Party   Street/Sidewalk       10034.0
1                         No Access   Street/Sidewalk       11105.0
2                         No Access   Street/Sidewalk       10458.0
3      Commercial Overnight Parking   Street/Sidewalk       10461.0
4                  Blocked Sidewalk   Street/Sidewalk       11373.0
...                             ...               ...           ...
47045                Partial Access   Street/Sidewalk       11358.0
47046                     No Access   Street/Sidewalk       10310.0
47047                     Neglected  Store/Commercial       11370.0
47048                     No Access   Street/Sidewalk       10453.0
47049              Loud Music/Party   Street/Sidewalk       10007.0

            Incident Address  ... Bridge Highway Name  \
0        71 VERMILYEA AVENUE  ...                 NaN
1            27-07 23 AVENUE  ...                 NaN
2      2897 VALENTINE AVENUE  ...                 NaN
3        2940 BAISLEY AVENUE  ...                 NaN
4              87-14 57 ROAD  ...                 NaN
...                      ...  ...                 ...
47045       43-61 161 STREET  ...                 NaN
47046        614 CARY AVENUE  ...                 NaN
47047                    NaN  ...                 NaN
47048     1685 JEROME AVENUE  ...                 NaN
47049         CITY HALL PARK  ...                 NaN

      Bridge Highway Direction Road Ramp Bridge Highway Segment  \
0                          NaN       NaN                    NaN
1                          NaN       NaN                    NaN
2                          NaN       NaN                    NaN
3                          NaN       NaN                    NaN
4                          NaN       NaN                    NaN
...                        ...       ...                    ...
47045                      NaN       NaN                    NaN
47046                      NaN       NaN                    NaN
47047                      NaN       NaN                    NaN
47048                      NaN       NaN                    NaN
47049                      NaN       NaN                    NaN

      Garage Lot Name Ferry Direction Ferry Terminal Name   Latitude  \
0                 NaN             NaN                 NaN  40.865682
1                 NaN             NaN                 NaN  40.775945
2                 NaN             NaN                 NaN  40.870325
3                 NaN             NaN                 NaN  40.835994
4                 NaN             NaN                 NaN  40.733060
...               ...             ...                 ...        ...
47045             NaN             NaN                 NaN  40.758377
47046             NaN             NaN                 NaN  40.632028
47047             NaN             NaN                 NaN  40.759330
47048             NaN             NaN                 NaN  40.846368
47049             NaN             NaN                 NaN        NaN

       Longitude                                  Location
0     -73.923501   (40.86568153633767, -73.92350095571744)
1     -73.915094  (40.775945312321085, -73.91509393898605)
2     -73.888525  (40.870324522111424, -73.88852464418646)
3     -73.828379   (40.83599404683083, -73.82837939584206)
4     -73.874170  (40.733059618956815, -73.87416975810375)
...          ...                                       ...
47045 -73.805185  (40.758377273679386, -73.80518542890631)
47046 -74.122167  (40.632028408561006, -74.12216666543866)
47047 -73.885104   (40.75933008575395, -73.88510434923467)
47048 -73.913316   (40.84636809667345, -73.91331613201108)
47049        NaN                                       NaN

[47050 rows x 53 columns]>

In [9]:
data.head()

,Unique Key,Created Date,Closed Date,Agency,Agency Name,Complaint Type,Descriptor,Location Type,Incident Zip,Incident Address,...,Bridge Highway Name,Bridge Highway Direction,Road Ramp,Bridge Highway Segment,Garage Lot Name,Ferry Direction,Ferry Terminal Name,Latitude,Longitude,Location
0,32310363,12/31/2015 11:59:45 PM,01/01/2016 12:55:15 AM,NYPD,New York City Police Department,Noise - Street/Sidewalk,Loud Music/Party,Street/Sidewalk,10034.0,71 VERMILYEA AVENUE,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.865682,-73.923501,"(40.86568153633767, -73.92350095571744)"
1,32309934,12/31/2015 11:59:44 PM,01/01/2016 01:26:57 AM,NYPD,New York City Police Department,Blocked Driveway,No Access,Street/Sidewalk,11105.0,27-07 23 AVENUE,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.775945,-73.915094,"(40.775945312321085, -73.91509393898605)"
2,32309159,12/31/2015 11:59:29 PM,01/01/2016 04:51:03 AM,NYPD,New York City Police Department,Blocked Driveway,No Access,Street/Sidewalk,10458.0,2897 VALENTINE AVENUE,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.870325,-73.888525,"(40.870324522111424, -73.88852464418646)"
3,32305098,12/31/2015 11:57:46 PM,01/01/2016 07:43:13 AM,NYPD,New York City Police Department,Illegal Parking,Commercial Overnight Parking,Street/Sidewalk,10461.0,2940 BAISLEY AVENUE,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.835994,-73.828379,"(40.83599404683083, -73.82837939584206)"
4,32306529,12/31/2015 11:56:58 PM,01/01/2016 03:24:42 AM,NYPD,New York City Police Department,Illegal Parking,Blocked Sidewalk,Street/Sidewalk,11373.0,87-14 57 ROAD,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.733060,-73.874170,"(40.733059618956815, -73.87416975810375)"

AttributeError: 'DataFrame' object has no attribute 'column'

In [13]:
data.columns

Index(['Unique Key', 'Created Date', 'Closed Date', 'Agency', 'Agency Name',
       'Complaint Type', 'Descriptor', 'Location Type', 'Incident Zip',
       'Incident Address', 'Street Name', 'Cross Street 1', 'Cross Street 2',
       'Intersection Street 1', 'Intersection Street 2', 'Address Type',
       'City', 'Landmark', 'Facility Type', 'Status', 'Due Date',
       'Resolution Description', 'Resolution Action Updated Date',
       'Community Board', 'Borough', 'X Coordinate (State Plane)',
       'Y Coordinate (State Plane)', 'Park Facility Name', 'Park Borough',
       'School Name', 'School Number', 'School Region', 'School Code',
       'School Phone Number', 'School Address', 'School City', 'School State',
       'School Zip', 'School Not Found', 'School or Citywide Complaint',
       'Vehicle Type', 'Taxi Company Borough', 'Taxi Pick Up Location',
       'Bridge Highway Name', 'Bridge Highway Direction', 'Road Ramp',
       'Bridge Highway Segment', 'Garage Lot Name', 'Ferry Direction',
       'Ferry Terminal Name', 'Latitude', 'Longitude', 'Location'],
      dtype='object')

In [14]:

pd.set_option('display.max_columns',None)
data.sample(4)

,Unique Key,Created Date,Closed Date,Agency,Agency Name,Complaint Type,Descriptor,Location Type,Incident Zip,Incident Address,Street Name,Cross Street 1,Cross Street 2,Intersection Street 1,Intersection Street 2,Address Type,City,Landmark,Facility Type,Status,Due Date,Resolution Description,Resolution Action Updated Date,Community Board,Borough,X Coordinate (State Plane),Y Coordinate (State Plane),Park Facility Name,Park Borough,School Name,School Number,School Region,School Code,School Phone Number,School Address,School City,School State,School Zip,School Not Found,School or Citywide Complaint,Vehicle Type,Taxi Company Borough,Taxi Pick Up Location,Bridge Highway Name,Bridge Highway Direction,Road Ramp,Bridge Highway Segment,Garage Lot Name,Ferry Direction,Ferry Terminal Name,Latitude,Longitude,Location
39287,32040185,11/21/2015 06:08:25 PM,11/21/2015 07:38:42 PM,NYPD,New York City Police Department,Noise - Street/Sidewalk,Loud Music/Party,Street/Sidewalk,10002.0,132 ESSEX STREET,ESSEX STREET,RIVINGTON STREET,STANTON STREET,NaN,NaN,ADDRESS,NEW YORK,NaN,Precinct,Closed,11/22/2015 02:08:25 AM,The Police Department responded to the complai...,11/21/2015 07:38:42 PM,03 MANHATTAN,MANHATTAN,987739.0,201614.0,Unspecified,MANHATTAN,Unspecified,Unspecified,Unspecified,Unspecified,Unspecified,Unspecified,Unspecified,Unspecified,Unspecified,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.720060,-73.987413,"(40.72005989206576, -73.98741330162642)"
39189,32039288,11/21/2015 08:19:46 PM,11/22/2015 02:27:06 AM,NYPD,New York City Police Department,Noise - Street/Sidewalk,Loud Music/Party,Street/Sidewalk,10033.0,611 WEST 180 STREET,WEST 180 STREET,ST NICHOLAS AVENUE,WADSWORTH AVENUE,NaN,NaN,ADDRESS,NEW YORK,NaN,Precinct,Closed,11/22/2015 04:19:46 AM,The Police Department responded to the complai...,11/22/2015 02:27:06 AM,12 MANHATTAN,MANHATTAN,1002327.0,248530.0,Unspecified,MANHATTAN,Unspecified,Unspecified,Unspecified,Unspecified,Unspecified,Unspecified,Unspecified,Unspecified,Unspecified,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.848814,-73.934660,"(40.84881397093934, -73.93466030980782)"
37228,32056802,11/23/2015 05:59:28 PM,11/23/2015 08:24:23 PM,NYPD,New York City Police Department,Blocked Driveway,No Access,Street/Sidewalk,11220.0,825 45 STREET,45 STREET,8 AVENUE,9 AVENUE,NaN,NaN,ADDRESS,BROOKLYN,NaN,Precinct,Closed,11/24/2015 01:59:28 AM,The Police Department responded to the complai...,11/23/2015 08:24:23 PM,12 BROOKLYN,BROOKLYN,984227.0,173719.0,Unspecified,BROOKLYN,Unspecified,Unspecified,Unspecified,Unspecified,Unspecified,Unspecified,Unspecified,Unspecified,Unspecified,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.643495,-74.000083,"(40.64349515386363, -74.00008287815236)"
41908,32023631,11/19/2015 10:28:11 AM,11/19/2015 10:08:33 PM,NYPD,New York City Police Department,Derelict Vehicle,With License Plate,Street/Sidewalk,11419.0,118-05 103 AVENUE,103 AVENUE,118 STREET,LEFFERTS BOULEVARD,NaN,NaN,ADDRESS,SOUTH RICHMOND HILL,NaN,Precinct,Closed,11/19/2015 06:28:11 PM,The Police Department reviewed your complaint ...,11/19/2015 10:07:26 PM,09 QUEENS,QUEENS,1032583.0,189894.0,Unspecified,QUEENS,Unspecified,Unspecified,Unspecified,Unspecified,Unspecified,Unspecified,Unspecified,Unspecified,Unspecified,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.687760,-73.825721,"(40.68775996597482, -73.82572123707524)"

In [15]:
data_mod = data.drop(columns=['Unique Key'],axis=1)

In [16]:
data_mod.columns

Index(['Created Date', 'Closed Date', 'Agency', 'Agency Name',
       'Complaint Type', 'Descriptor', 'Location Type', 'Incident Zip',
       'Incident Address', 'Street Name', 'Cross Street 1', 'Cross Street 2',
       'Intersection Street 1', 'Intersection Street 2', 'Address Type',
       'City', 'Landmark', 'Facility Type', 'Status', 'Due Date',
       'Resolution Description', 'Resolution Action Updated Date',
       'Community Board', 'Borough', 'X Coordinate (State Plane)',
       'Y Coordinate (State Plane)', 'Park Facility Name', 'Park Borough',
       'School Name', 'School Number', 'School Region', 'School Code',
       'School Phone Number', 'School Address', 'School City', 'School State',
       'School Zip', 'School Not Found', 'School or Citywide Complaint',
       'Vehicle Type', 'Taxi Company Borough', 'Taxi Pick Up Location',
       'Bridge Highway Name', 'Bridge Highway Direction', 'Road Ramp',
       'Bridge Highway Segment', 'Garage Lot Name', 'Ferry Direction',
       'Ferry Terminal Name', 'Latitude', 'Longitude', 'Location'],
      dtype='object')

In [17]:

pd.unique(data['Agency'])

array(['NYPD'], dtype=object)

In [18]:
data['Agency'].value_counts()

NYPD    47050
Name: Agency, dtype: int64

In [19]:
data_mod = data_mod.drop(columns=['Agency'],axis=1)

In [20]:
pd.unique(data['Agency Name'])

array(['New York City Police Department', 'NYPD'], dtype=object)

In [21]:
data['Agency Name'].value_counts()

New York City Police Department    47049
NYPD                                   1
Name: Agency Name, dtype: int64

In [22]:
data['Complaint Type'].value_counts().head(5)

Blocked Driveway           14876
Illegal Parking            13519
Noise - Commercial          6206
Noise - Street/Sidewalk     4052
Derelict Vehicle            2829
Name: Complaint Type, dtype: int64

In [23]:
data.Descriptor.value_counts().head(5)

No Access                        11164
Loud Music/Party                  6933
Posted Parking Sign Violation     4030
Partial Access                    3712
Blocked Hydrant                   3118
Name: Descriptor, dtype: int64

In [24]:
data['Location Type'].value_counts().head(4)

Street/Sidewalk               39052
Store/Commercial               3694
Club/Bar/Restaurant            2850
Residential Building/House      985
Name: Location Type, dtype: int64

In [25]:
data['Incident Zip'].value_counts().head(4)

11385.0    970
11368.0    769
11234.0    655
11230.0    654
Name: Incident Zip, dtype: int64

In [26]:
data['Incident Address'].value_counts().head(4)

1207 BEACH AVENUE          244
78-15 PARSONS BOULEVARD    187
514 WEST 44 STREET         166
177 LAREDO AVENUE          116
Name: Incident Address, dtype: int64

In [27]:
data['Street Name'].value_counts().head(5)

BROADWAY             542
BEACH AVENUE         275
WEST 44 STREET       255
PARSONS BOULEVARD    219
SHERMAN AVENUE       211
Name: Street Name, dtype: int64

In [28]:
data['Cross Street 1'].value_counts().head(4)

BEND        656
3 AVENUE    560
BROADWAY    523
5 AVENUE    425
Name: Cross Street 1, dtype: int64

In [29]:
data['Cross Street 2'].value_counts().head(4)

BEND        618
BROADWAY    488
8 AVENUE    378
DEAD END    326
Name: Cross Street 2, dtype: int64

In [30]:
data['Intersection Street 1'].value_counts().head(4)

BROADWAY            90
78 AVENUE           50
EAST   46 STREET    50
1 AVENUE            37
Name: Intersection Street 1, dtype: int64

In [31]:
data['Intersection Street 2'].value_counts().head(4)

BROADWAY    176
2 AVENUE    114
3 AVENUE     71
1 AVENUE     71
Name: Intersection Street 2, dtype: int64

In [32]:
data['Address Type'].value_counts().head(4)

ADDRESS         39331
INTERSECTION     5347
BLOCKFACE        1488
LATLONG           515
Name: Address Type, dtype: int64

In [33]:
data['City'].value_counts().head(4)

BROOKLYN         16020
NEW YORK          9477
BRONX             5776
STATEN ISLAND     2176
Name: City, dtype: int64

In [34]:
data.Landmark.value_counts().head(5)

CENTRAL PARK              6
J F K AIRPORT             3
MADISON SQUARE GARDEN     2
UNION SQUARE PARK         2
WASHINGTON SQUARE PARK    2
Name: Landmark, dtype: int64

In [35]:
data['Facility Type'].value_counts()

Precinct    46795
Name: Facility Type, dtype: int64

In [36]:
data.Status.value_counts()

Closed      46790
Open          177
Assigned       82
Draft           1
Name: Status, dtype: int64

In [37]:
data['Due Date'].value_counts().head(4)

12/24/2015 02:33:50 AM    3
12/28/2015 08:00:04 PM    2
11/30/2015 07:11:33 PM    2
11/24/2015 08:26:56 PM    2
Name: Due Date, dtype: int64

In [38]:
data['Resolution Description'].value_counts().head(4)

The Police Department responded to the complaint and with the information available observed no evidence of the violation at that time.    13695
The Police Department responded and upon arrival those responsible for the condition were gone.                                             9772
The Police Department responded to the complaint and took action to fix the condition.                                                      8396
The Police Department responded to the complaint and determined that police action was not necessary.                                       6040
Name: Resolution Description, dtype: int64

In [39]:
data['School Name'].value_counts()

Unspecified    47050
Name: School Name, dtype: int64

In [4]:
data['School Number'].value_counts()

NameError: name 'data' is not defined

In [5]:
data['School Region'].value_counts()

NameError: name 'data' is not defined

In [6]:
data['School Not Found'].value_counts()

NameError: name 'data' is not defined

In [7]:
data.shape

NameError: name 'data' is not defined

In [ ]:
data.describe()